name: Dispatcher Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name to map to a workflow"
        required: true
        type: choice
        options:
          - "2024"
          - "2025"

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
          workflow=${{ github.event.inputs.branch }}.yaml
          echo "Triggering workflow: $workflow"
          gh workflow run "$workflow"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
